### ISSUE TITLE
Usage refers to block.sh

### ISSUE THREAD

**Issue by mattburchett** [AndrewPaglusch/IPTables-Easy-Drop#1]
The usage in the script refers to a script called `block.sh` instead of `drop.sh`.

https://github.com/AndrewPaglusch/IPTables-Easy-Drop/blob/ebc60066124b23bfc7f159892c04413650be02ee/drop.sh#L4-L9

**Comment by AndrewPaglusch** [comment]
Thank you for letting me know. This has been corrected. 448b423f
